const doorprizes = [
    { Name: "Isyana Shahia Abichandra", Doorprizes: "TAS SEPEDA" },
    { Name: "LAVANYA RASA EL SADARA", Doorprizes: "KAOS KAKI P.K JATIWANGI" },
    { Name: "Andari Tisa Almahira", Doorprizes: "KAOS KAKI P.K JATIWANGI" },
    { Name: "SAIA SADDAM EL SAAD", Doorprizes: "KAOS KAKI P.K JATIWANGI" },
    { Name: "Prince Shaquille Alfarezel", Doorprizes: "KAOS ANAK JUSTICE OF REBBEL" },
    { Name: "Sarah Arunika Najma", Doorprizes: "KAOS ANAK JUSTICE OF REBBEL" },
    { Name: "Haidar Arshaka Husein", Doorprizes: "KAOS ANAK ORLIN GARAGE" },
    { Name: "El shaquille", Doorprizes: "KAOS ANAK ORLIN GARAGE" },
    { Name: "jane zeba alvaris", Doorprizes: "KURSI LIPAT CV SUMBER MAJU AGROINDO" },
    { Name: "Umair Abdillah El Rio", Doorprizes: "KURSI LIPAT CV SUMBER MAJU AGROINDO" },
    { Name: "Ameera Zivana", Doorprizes: "KURSI LIPAT RAZENDRA 143" },
    { Name: "Arqam Wigata", Doorprizes: "KURSI LIPAT RAZENDRA 143" },
    { Name: "Kirana Aleta Putri", Doorprizes: "KURSI LIPAT RAZENDRA 143" },
    { Name: "Fawwaz Abil Syathibi Arsalaan", Doorprizes: "KURSI LIPAT RAZENDRA 143" },
    { Name: "safiya fitils n alhakim", Doorprizes: "KURSI LIPAT RAZENDRA 143" },
    { Name: "rafisqy haziq munandar", Doorprizes: "HANDGRIP ROCKBROSH (FAVIAN)" },
    { Name: "Rania Farhanah", Doorprizes: "HANDGRIP ROCKBROSH (FAVIAN)" },
    { Name: "Kheyra Ghazala Putri Jurangga", Doorprizes: "HANDGRIP ROCKBROSH (FAVIAN)" },
    { Name: "Favian Mahasin Alfarizy", Doorprizes: "HANDGRIP ROCKBROSH (FAVIAN)" },
    { Name: "Shakina Haura Chadafy", Doorprizes: "HANDGRIP ROCKBROSH (FAVIAN)" },
    { Name: "Pramanathan Ganesh Adiwijaya", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "Shakila Qisya Nurul Adzkiya", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "beniarfian putra hermawan", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "Langit Pranaditba Berlain", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "Safaniya Khadijah Afsheen", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "Najma Fajrina Orlin", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "Alvano Rafandra Anugrah", Doorprizes: "TOPI BERACE APPAREL" },
    { Name: "NIANA ANASERA DESTI", Doorprizes: "PUZZLE BOX (NUHA)" },
    { Name: "Cairo thufail", Doorprizes: "PUZZLE BOX (NUHA)" },
    { Name: "Hilya Divana Adzkia", Doorprizes: "PUZZLE BOX (NUHA)" },
    { Name: "Alexander Melva Ibrahim", Doorprizes: "PUZZLE BOX (NUHA)" },
    { Name: "Razendra Arsenio Ferdian", Doorprizes: "PUZZLE BOX (NUHA)" },
    { Name: "Moh. Gavin Alhafidz", Doorprizes: "CELANA ANAK (ARKANZA)" },
    { Name: "Muhammad Rajendra Satria", Doorprizes: "CELANA ANAK (ARKANZA)" },
    { Name: "Aaron Shafeeq Mafaza", Doorprizes: "SET MENGGUNTING KERTAS (MANUNNO)" },
    { Name: "Ringga enzio priyadi", Doorprizes: "SET MENGGUNTING KERTAS (MANUNNO)" },
    { Name: "GEMINTANG MUHAMMAD", Doorprizes: "SET MENGGUNTING KERTAS (MANUNNO)" },
    { Name: "NOVANIA AYUDIA SHANUM", Doorprizes: "LUNCH BOX (MOCI)" },
    { Name: "najelaa humaira basri", Doorprizes: "LUNCH BOX (MOCI)" },
    { Name: "Khayra Shuri Dianta", Doorprizes: "LUNCH BOX (MOCI)" },
    { Name: "Marcello Abrisam Raynan", Doorprizes: "TUMBLR (MALIK)" },
    { Name: "Owen Khaleed Syaquille", Doorprizes: "TUMBLR (MALIK)" },
    { Name: "SHAQUILLE IBRAHIM MEIDY", Doorprizes: "TUMBLR (MALIK)" },
    { Name: "NAZEERA ZEBA", Doorprizes: "TUMBLR (MALIK)" },
    { Name: "Khalisa Divana Aghnia", Doorprizes: "TUMBLR (MALIK)" },
    { Name: "Kin Dhananjaya Kurniawan", Doorprizes: "LUNCH BOX (BAIM)" },
    { Name: "ABDUL MALIK PERDANA", Doorprizes: "LUNCH BOX (BAIM)" },
    { Name: "Arunika Wafa Abqura", Doorprizes: "BOTOL MINUM ANAK (NAJMA)" },
    { Name: "Iyqy Keanu", Doorprizes: "BOTOL MINUM ANAK (NAJMA)" },
    { Name: "Alvino Raffasya Anugrah", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Gelzan eljio arwi", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Avneina Shaquilla Rinosa", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Shahia Asheeq Zara", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Muhammad Zaidan Alfath", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Aleeya nafeeza rafanda", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "KAYLA AZKIYA RAHMAN", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Ananda Ozil Al Fikri", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Cut Alesha Ferinda", Doorprizes: "MAINAN EDUKASI (NALENDRA)" },
    { Name: "Keenan Guiza datmawan", Doorprizes: "MAINAN EDUKASI (NALENDRA)" }
];

export default doorprizes;
