// lib/rules.js

const rules = [
    ('REGULASI SEPEDA', [
        "SEPEDA YANG DIGUNAKAN ADALAH SEPEDA PUSHBIKE/BALANCE BIKA YANG SESUAI DENGAN UKURAN RODA 12 INCH",
        "PANJANG HANDLEBAR MAX 48CM DAN WAJIB MENGGUNAKAN BAR END KARET / PLASTIK",
        "WAJIB MENGGUNAKAN STEM PROTECTOR DEMI KEAMANAN RIDER",
        "DILARANG MENAMBAH REM DAN LAMPU YANG DAPAT MENGGANGGU JALANNYA PERLOMBAAN DAN MEMBAHAYAKAN UNTUK RIDERS SERTA PESERTA LAINNYA"
    ]),
    ('REGULASI RIDERS', [
        "RIDER WAJIB MENGGUNAKAN HELM DAN TALI WAJIB DIKAITKAN, AKAN ADA PENALTY POIN +5 APABILA MELANGGAR KETENTUAN",
        "RIDERS WAJIB MENGGUNAKAN SEPATU DAN KAOS KAKI KETIKA AKAN START, AKAN ADA PENALTY POIN +5 APABILA MELANGGAR KETENTUAN",
        "DILARANG KERAS MENGGUNAKAN ORNAMENT LAMPU ATAU SEJENISNYA DIHELM, SEPATU, MAUPUN BAJU/JERSEY YANG DAPAT MENGGANGGU KONSENTRASI PESERTA LAIN, AKAN ADA PENALTY POINT +5 JIKA KETENTUAN INI DILANGGAR",
        "DISARANKAN UNTUK MENGGUNAKAN ALAT KESELAMATAN TAMBAHAN SEPERTI SARUNG TANGAN, KNEE DAN ELBOW PROTECTOR",
        "RIDERS WAJIB MENGGUNAKAN NUMBER PLATE BERACE YANG SUDAH DIBAGIKAN KETIKA REGISTRASI, APABILA TIDAK MEMAKAI MAKA RIDERS DIANGGAP DNS (DID NOT START)",
        "RIDERS WAJIB MENGIKUTI KELAS SESUAI TAHUN LAHIR DAN GENDERNYA (BOY DAN GIRL) ATAU NAIK KELAS DIATASNYA. DILARANG KERAS UNTUK TURUN KELAS ATAU MELAKUKAN KECURANGAN DATA UNTUK BALAPAN DENGAN USIA DIBAWAHNYA YANG LEBIH MUDA, APABILA TERBUKTI MELANGGAR MAKA RIDERS DINYATAKAN GUGUR DAN DILARANG SELAMANYA MENGIKUTI SELURUH EVENT BERACE X PUSHBIKE LAMPUNG ACADEMY"
    ]),
    ('REGULASI WALI RIDERS', [
        "WALI TIDAK DIPERKENANKAN MEMASUKI AREA TRACK / AREA STERIL YANG TELAH DITENTUKAN RACE DIRECTOR (WALI DIPERKENANKAN MASUK KE TRACK SETELAH MENDAPATKAN PERSETUJUAN RACE DIRECTOR APABILA RIDERS TERJATUH DAN TIDAK MAU MELANJUTKAN RACE)",
        "WALI HARUS BERJARAK MINIMAL 1,5 METER DARI RIDERS KETIKA START DAN DILARANG MENYENTUH RIDER, APABILA TERBUKTI MELANGGAR PENALTY POIN +5",
        "WALI DILARANG MEMASUKI AREA FINISH YANG TELAH DITENTUKAN, APABILA MELANGGAR AKAN ADA PENALTY POIN +5",
        "HANYA BOLEH ADA MAX 2 WALI RIDERS DAN 1 PELATIH SETIAP TIM/KOMUNITAS YANG DIPERKENANKAN MEMBANTU RIDERNYA DIWAITING ZONE",
        "WALI RIDER DILARANG MENGGUNAKAN ALAT BANTU KOMUNIKASI / PROPERTY YANG DAPAT MENGGANGGU KONSENTRASI RIDERS LAIN",
        "WALI RIDERS WAJIB MENJAGA ETIKA, KESOPANAN, KEAMANAN, KENYAMANAN DAN KEBERSIHAN SELAMA RACE BERLANGSUNG, APABILA TERBUKTI MELANGGAR MAKA PANITIA BERHAK MENEGUR DAN MENINDAK SESUAI HUKUM UU YANG BERLAKU"

    ]),
    ('REGULASI PERLOMBAAN', [
        "DILARANG MENAMBAH ALAT PEREKAM DI SEPEDA, HELM ATAU BAGIAN TUBUH RIDERS",
        "APABILA RIDER MEMBAWA DOKUMENTASI PRIBADI, DILARANG MEMASUKI AREA TRACK, DOKUMENTASI PRIBADI HANYA DIPERKENANKAN DI LUAR TRACK DAN TIDAK MENGGANGGU AREA DOKUMENTASI DARI PENYELENGGARA",
        "RACE AKAN DILAKUKAN DENGAN 6 LINE GATE START.",
        "PERHITUNGAN POIN MENGGUNAKAN SISTEM POIN TERENDAH YANG AKAN MELANJUTKAN KE TAHAP SELANJUTNYA P1 MENDAPATKAN POINT 1, P2 MENDAPATKAN POINT 2, P3 MENDAPATKAN POINT 3, DST...",
        "UNTUK KELAS YANG HANYA ADA 1 GRUP, AKAN MEMAINKAN 3X MOTO DENGAN GATE YANG BERBEDA DAN JUARA AKAN DITENTUKAN DENGAN MENGHITUNG PEROLEHAN POINT YANG AKAN DIURUTKAN DARI YANG TERENDAH KE YANG TERBESAR, APABILA ADA PERSAMAAN POIN MAKA PENENTUAN POSISI PODIUM MELIHAT DARI POSISI FINISH MOTO TERAKHIR",
        "KELAS YANG TERDIRI DARI 2 GRUP AKAN MEMAINKAN 2X MOTO DENGAN GATE YANG BERBEDA, PERINGKAT 1-3 SETIAP GRUP MENUJU FINAL UTAMA, PERINGKAT 4-6 SETIAP GRUP MENUJU FINAL NOVICE (KHUSUS KELAS FFA TIDAK ADA FINAL NOVICE, HANYA FINAL UTAMA)",
        "KELAS YANG TERDIRI DARI 3 GRUP AKAN MEMAINKAN 2X MOTO DENGAN GATE YANG BERBEDA, PERINGKAT 1-4 SETIAP GRUP AKAN MENUJU BABAK SEMIFINAL, PADA BABAK SEMIFINAL PERINGKAT 1-3 SETIAP GRUP SEMIFINAL MENUJU FINAL UTAMA, PERINGKAT 4-6 SETIAP GRUP SEMIFINAL MENUJU FINAL NOVICE (KHUSUS KELAS FFA TIDAK ADA FINAL NOVICE, HANYA FINAL UTAMA)",
        "KELAS YANG TERDIRI DARI 4 GRUP AKAN MEMAINKAN 2X MOTO DENGAN GATE YANG BERBEDA, PERINGKAT 1-3 SETIAP GRUP AKAN MENUJU BABAK SEMIFINAL, PADA BABAK SEMIFINAL PERINGKAT 1-3 SETIAP GRUP SEMIFINAL MENUJU FINAL UTAMA, PERINGKAT 4-6 SETIAP GRUP SEMIFINAL MENUJU FINAL NOVICE (KHUSUS KELAS FFA TIDAK ADA FINAL NOVICE, HANYA FINAL UTAMA)",
        "KELAS YANG TERDIRI DARI 5 GRUP AKAN MEMAINKAN 2X MOTO DENGAN GATE YANG BERBEDA, PERINGKAT 1-4 SETIAP GRUP AKAN MENUJU BABAK QUARTER FINAL, PADA BABAK QUARTER FINAL PERINGKAT 1-3 SETIAP GRUP MENUJU BABAK SEMIFINAL, PADA BABAK SEMIFINAL PERINGKAT 1-3 SETIAP GRUP SEMIFINAL MENUJU FINAL UTAMA, PERINGKAT 4-6 SETIAP GRUP SEMIFINAL MENUJU FINAL NOVICE (KHUSUS KELAS FFA TIDAK ADA FINAL NOVICE, HANYA FINAL UTAMA)",
        "DALAM SATU GRUP MAKSIMAL HANYA AKAN BERISI 6 RIDERS YANG ARTINYA AKAN ADA 6 FINALIS YANG AKAN MEMPEREBUTKAN PODIUM UTAMA DAN NOVICE DI SETIAP KELASNYA",
        "DALAM SISTEM MOTO JIKA TERJADI POIN YANG SAMA, MAKA AKAN DILIHAT DARI PERINGKAT TERBAIK KETIKA FINISH DI MOTO TERAKHIR UNTUK MENENTUKAN POSISI YANG LEBIH BAIK",
        "PETUGAS PEMANGGILAN START HANYA MEMANGGIL SEBANYAK 3X SELANJUTNYA RIDERS AKAN DIANGGAP DNS (DID NOT START) APABILA TIDAK SEGERA BERSIAP DI GATE START",
        "RIDERS YANG TIDAK MENYELESAIKAN FINISH SETIAP BABAK MAKA AKAN DIANGGAP DNF (DID NOT FINISH) DAN AKAN DIBERIKAN PENALTY POIN +6",
        "DALAM MELAKUKAN START SELURUH RIDERS DILARANG BERGERAK MELOMPATI GATE START YANG BENAR – BENAR TERBUKA, APABILA GATE BELUM – BELUM TERBUKA DAN RODA TERLIHAT MENAIKI GATE START MAKA DIANGGAP MELAKUKA JUMP START DAN DIKENAKAN PENALTY POIN +4",
        "APABILA KETIKA MELAKUKAN START DAN RIDERS TERJATUH MINIMAL ½ DARI TOTAL JUMLAH STARTER SEBELUM MELEWATI RED LINE (SELURUH PERMUKAAN GATE START), MAKA START AKAN DIULANG MAKSIMAL 1X.",
        "SELURUH RIDERS DILARANG MENGAMBIL OVERTAKE YANG MEMBAHAYAKAN RIDERS LAIN ATAU MENGAKIBATKAN BENTURAN ANTAR RIDERS (MENYUDUTKAN RIDERS LAIN KE ARAH BATAS TRACK, SEHINGGA RIDERS LAIN HARUS MEMPERLAMBAT LAJU ATAU BAHKAN TERJATUH MENABRAK PEMBATAS TRACK) AKAN DIANGGAP MELAKUKAN PELANGGARAN, APABILA MELAKUKAN AKAN PENALTY POINT +4",
        "MANUVER BERBAHAYA, APABILA RIDERS KEDAPATAN SENGAJA MENABRAK RIDERS DIDEPANNYA HINGGA RIDERS DIDEPANNYA TERJATUH DI TRACK LURUS MAUPUN BELOKAN MAKA DIANGGAP PELANGGARAN DAN DIKENAKAN PENALTY POIN +4",
        "SELURUH RIDERS DILARANG KERANG MENEROBOS ATAU MELAKUKAN SHORTCUT LINTASAN YANG TELAH DITENTUKAN, APABILA TERJADI MAKAN PENALTY POIN +4 APABILA TERBUKTI MELANGGAR",
        "RACE DIRECTOR AKAN MENGAMBIL SIKAP JIKA ADA KEBERATAN YANG DIAJUKAN TERHADAP SALAH SATU RIDERS TERKAIT PELANGGARAN DI POIN 14, 16, 17, 18. PENGAJUAN KEBERATAN WAJIB MENYERTAKAN VIDEO YANG JELAS SEBAGAI BUKTI. APABILA TIDAK DAPAT MENYERTAKAN VIDEO SEBAGAI BUKTI MAKAN RACE DIRECTOR BERHAK MENGAMBIL SIKAP BAHWA RACE BERJALAN NORMAL TANPA ADANYA PELANGGARAN",
        "MARSHALL AKAN BERTUGAS MENJAGA KEAMANAN TRACK (STERIL DARI PENGUNJUNG, KEBERSIHAN PERMUKAAN TRACK, DAN PEMBATAS YANG TERPASANG BAIK DAN BENAR) SERTA MEMBANTU RIDERS YANG TERJATUH SETELAH SELURUH RIDERS LAIN MELEWATI RIDERS YANG TERJATUH",
        "MARSHALL DAPAT SEGERA MEMBANTU RIDERS YANG TERJATUH APABILA DI LUAR RACING LINE ATAU DINILAI AMAN DAN TIDAK MENGGANGGU RIDERS LAIN TANPA HARUS MENUNGGU SELURUH RIDERS MELEWATINYA",
        "MARSHALL BERHAK MENGHENTIKAN RACE KETIKA START BELUM DIMULAI APABILA DITEMUKAN HAL – HAL YANG MENGANGGU KEAMANAN RIDERS KETIKA DI TRACK",
        "MARSHALL HANYA AKAN MENYENTUH SEPEDA ANAK YANG TERJATUH DAN MEMASTIKAN SEPEDA SIAP DIGUNAKAN RIDERS, MARSHALL BARU MENYENTUH RIDERS APABILA RIDERS BERADA DIPOSISI YANG TIDAK AMAN ATAU TIDAK BISA BANGUN SENDIRI (TERTIMPA SEPEDA SENDIRI, SEPEDA RIDERS LAIN, ATAU TERTIMPA RIDERS LAIN YANG TERJATUH)",
        "APABILA ADA RIDERS YANG MASUK GARIS FINISH HAMPIR BERSAMAAN, MAKA AKAN DITENTUKAN POSISI FINISH MELALUI REKAMAN VIDEO SEBAGAI BUKTI DIMANA RODA DEPAN YANG TERLEBIH DAHULU MENYENTUH GARIS FINISH YANG AKAN DINYATAKAN SEBAGAI POSISI FINISH YANG LEBIH BAIK",
        "SETIAP KATEGORI RACE AKAN DIAWALI KATEGORI GENDER GIRL",
        "APABILA TERJADI FORCE MAJUERE DALAM JALANNYA RACE MAKA RACE DIRECTOR BERHAK MEMBERHENTIKAN JALANNYA RACE DAN MELAKUKAN MUSYAWARAH DENGAN PERWAKILAN PESERTA UNTUK MEMUTUSKAN KELANJUTAN RACE TERSEBUT",
        "DALAM PENYAMPAIAN ATAU MENGAJUKAN KEBERATAN TERHADAP JALANNYA RACE WAJIB DISAMPAIKAN SECARA LANGSUNG MELALUI RACE DIRECTORDISERTAI VIDEO BUKTI. PROSES PENGAJUAN KEBERATAN WAJIB DISAMPAIKAN SEBELUM RACE SELANJUTNYA BERLANGSUNG. KEBERATAS YANG DIAJUKAN SETELAH RACE SELANJUTNYA BERLANGSUNG DIANGGAP GUGUR."
    ])
];

export default rules;
